Feature/gen 2 themes
GoldElysium/hefs-website pull request #261
Opened 2022-05-01 16:49 UTC by JackCrescend

Adds themes for IRyS + gen 2 holoMembers

All development / deployment guild ID's should now correspond to a matching theme and be applied correctly.

2022-05-01 17:56 UTC, GoldElysium requested changes
Codacy is rightfully complaining about missing spaces, can you go through those notices?

2022-05-01 18:47 UTC, JackCrescend commented
> Codacy is rightfully complaining about missing and sometimes too many spaces, can you go through those notices?

Adding and removing the spaces sure, but Codacy seems to also complain about (no-descending-specificity) because I grouped the CSS rules per theme together. I'd have to split theme-specific link color rules hundreds of lines away from the rest of the theme specifications. Now I can fix those warnings, I just think It'd make the themes harder to maintain / update down the line. Shall I do it anyways?

2022-05-02 07:38 UTC, GoldElysium commented
> > Codacy is rightfully complaining about missing and sometimes too many spaces, can you go through those notices?
> 
> Adding and removing the spaces sure, but Codacy seems to also complain about (no-descending-specificity) because I grouped the CSS rules per theme together. I'd have to split theme-specific link color rules hundreds of lines away from the rest of the theme specifications. Now I can fix those warnings, I just think It'd make the themes harder to maintain / update down the line. Shall I do it anyways?

Nope, my concern was only with the spaces. You can keep them grouped by theme

2022-05-02 15:09 UTC, GoldElysium approved these changes

2022-05-02 15:10 UTC, merged